
version: "3.5"
services:
  rabbitmq:
    image: artifactory:9090/poo-virtual-docker/vmware-tanzu-rabbitmq:1.4.1_3.11.8
    container_name: go-rabbit
    restart: always
    expose:
      - 5552
    ports:
      - "9090:15672"
      - "9089:15671"
      - "5672:5672"
      - "5552:5552"
    environment:
      - TZ=Asia/Tokyo
      - RABBITMQ_NODENAME=${RABBITMQ_NODENAME}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - /rabbitmq/mnesia:/var/lib/rabbitmq/mnesia
      - /opt/deployments/rabbitmq/rabbitmqConfig:/etc/rabbitmq
      - /etc/pki/tls/certs/rabbitmq:/etc/pki/tls/certs/rabbitmq